version: '2'
services:
  consul:
    image: consul
    network_mode: host
    command: agent -server -ui -bind 0.0.0.0 -advertise 172.20.1.20 -client 0.0.0.0 -log-level err -bootstrap-expect=1
  vault:
    image: vault
    network_mode: host
    command: server -dev
