version: '2'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.2
    ports:
      - "2380:2380"
      - "2379:2379"
    command:
      - etcd
      - -name=etcd
      - -listen-client-urls=http://0.0.0.0:2379
      - -advertise-client-urls=http://0.0.0.0:2379
