version: '2'
services:
  consul:
    image: consul
    network_mode: host
    command: agent -server -ui -bind 0.0.0.0 -advertise 172.20.1.20 -client 0.0.0.0 -log-level err -bootstrap-expect=1
  vault:
    image: vault
    network_mode: host
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_LOCAL_CONFIG: '{"listener": {"tcp": {"address": "0.0.0.0:8200", "tls_disable": true}}, "backend": {"consul": {}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
    command: server
